-- Enable Row Level Security
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- Categories Table
create table public.categories (
  id uuid not null default gen_random_uuid (),
  name text not null,
  image text null,
  description text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint categories_pkey primary key (id)
);

-- Plants Table
create table public.plants (
  id uuid not null default gen_random_uuid (),
  name text not null,
  description text not null,
  care_instructions text null,
  fertilizing_info text null,
  usage_info text null,
  tags text[] null,
  category_id uuid null,
  price numeric null,
  discount numeric null,
  stock integer null default 0,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  
  constraint plants_pkey primary key (id),
  constraint plants_category_id_fkey foreign key (category_id) references categories (id)
);

-- Plant Variants Table (Normalized)
create table public.plant_variants (
  id uuid not null default gen_random_uuid (),
  plant_id uuid not null,
  size text not null,
  price numeric not null,
  discount numeric null,
  stock integer not null default 0,
  is_active boolean not null default true,
  growth_rate text null,
  height text null,
  weight text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  
  constraint plant_variants_pkey primary key (id),
  constraint plant_variants_plant_id_fkey foreign key (plant_id) references plants (id) on delete cascade
);

-- Settings Table
-- Converted from user request (MySQL -> Postgres)
DO $$ BEGIN
    create type public.setting_type_enum as enum (
      'text','number','email','phone',
      'url','image','boolean','date'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

create table if not exists public.settings (
  setting_id bigint generated by default as identity primary key,
  setting_key text not null unique,
  setting_value text,
  setting_type public.setting_type_enum not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Plant Images Table (Normalized)
create table public.plant_images (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  plant_id uuid not null,
  image_url text not null,
  is_primary boolean not null default false,
  display_order integer not null default 0,
  
  constraint plant_images_pkey primary key (id),
  constraint plant_images_plant_id_fkey foreign key (plant_id) references plants (id) on delete cascade
);

-- RLS Policies (Start open for read, restricted for write)
alter table public.plants enable row level security;
alter table public.categories enable row level security;
alter table public.plant_variants enable row level security;
alter table public.plant_images enable row level security;
alter table public.settings enable row level security;

-- Plants Policies
drop policy if exists "Public Plants Read" on public.plants;
create policy "Public Plants Read" on public.plants for select using (true);

drop policy if exists "Admin Plants All" on public.plants;
create policy "Admin Plants All" on public.plants for all using (auth.role() = 'authenticated');

-- Categories Policies
drop policy if exists "Public Categories Read" on public.categories;
create policy "Public Categories Read" on public.categories for select using (true);

drop policy if exists "Admin Categories All" on public.categories;
create policy "Admin Categories All" on public.categories for all using (auth.role() = 'authenticated');

-- Variants Policies
drop policy if exists "Public Variants Read" on public.plant_variants;
create policy "Public Variants Read" on public.plant_variants for select using (true);

drop policy if exists "Admin Variants All" on public.plant_variants;
create policy "Admin Variants All" on public.plant_variants for all using (auth.role() = 'authenticated');

-- Images Policies
drop policy if exists "Public Images Read" on public.plant_images;
create policy "Public Images Read" on public.plant_images for select using (true);

drop policy if exists "Admin Images All" on public.plant_images;
create policy "Admin Images All" on public.plant_images for all using (auth.role() = 'authenticated');

-- Settings Policies
drop policy if exists "Public Settings Read" on public.settings;
create policy "Public Settings Read" on public.settings for select using (true);

drop policy if exists "Admin Settings All" on public.settings;
create policy "Admin Settings All" on public.settings for all using (auth.role() = 'authenticated');

-- Storage Bucket for Images
insert into storage.buckets (id, name, public) values ('plants', 'plants', true) ON CONFLICT (id) DO NOTHING;
insert into storage.buckets (id, name, public) values ('common_images', 'common_images', true) ON CONFLICT (id) DO NOTHING;

drop policy if exists "Public Image Read" on storage.objects;
create policy "Public Image Read" on storage.objects for select using ( bucket_id in ('plants', 'common_images') );

drop policy if exists "Admin Image Upload" on storage.objects;
create policy "Admin Image Upload" on storage.objects for insert with check ( bucket_id in ('plants', 'common_images') and auth.role() = 'authenticated' );
